WIP - #9 - Create a box component
safient/safient-client pull request #22
Opened 2021-08-24 19:53 UTC by cksadhukhan

Description: 
 - Box component added

2021-08-26 05:09 UTC, dsouzaedison requested changes

2021-08-26 05:09 UTC, dsouzaedison commented on src/components/primitive/box/box.component.props.ts
> +  height?: number | string;
Height/width can be a string?

2021-08-26 12:05 UTC, koshikraj commented on src/components/primitive/box/box.component.props.ts
> +  height?: number | string;
It makes sense if we are passing the type along with it (Ex: `10px`, `1rem`). I think we haven't defined any standard type for this.

2021-08-26 12:35 UTC, chanchal-sadhukhan commented on src/components/primitive/box/box.component.props.ts
> +  height?: number | string;
we are using rem

2021-08-26 14:00 UTC, dsouzaedison approved these changes

2021-08-26 14:03 UTC, dsouzaedison commented
Wait for @Koushith to merge his PR's (#7 and #10 )

2021-08-27 09:07 UTC, dsouzaedison commented
Update this PR with theming changes by taking the latest from develop.

2021-08-27 09:11 UTC, chanchal-sadhukhan commented
I'll update the theming

2021-08-27 18:13 UTC, merged