#10 - Create a box component
safient/safient-client pull request #24
Opened 2021-08-25 11:37 UTC by Koushith

### Description

- [x] restructured color and palette files.
- [x] removed nested objects and named them according to context.

2021-08-26 05:22 UTC, dsouzaedison requested changes

2021-08-26 05:22 UTC, dsouzaedison commented on src/components/primitive/Icon-svg/icon-svg.component.style.ts
> +export const SvgWrapper = styled.div<{ size: number; color: string }>`
Color cannot be a string. We should only support the ones that are specified in our theme.

2021-08-26 05:22 UTC, dsouzaedison commented on src/components/primitive/Icon-svg/icon-svg.component.tsx
> +    <SvgWrapper size={size ?? 14} color={iconColor} {...rest}>
Why is `14` hard-coded? No hard-coding of values. Every constant must be declared with the appropriate name.

2021-08-26 05:22 UTC, dsouzaedison commented on src/screens/home/home.screen.tsx
> +          <IconSvg name='add' color='black' size={60} />
@Koushith Please note, do not push test data while you raise PRs. PRs must contain only the work mentioned in the tickets.

2021-08-26 11:41 UTC, dsouzaedison requested changes

2021-08-26 11:41 UTC, dsouzaedison commented on src/components/primitive/Icon-svg/icon-svg.component.props.ts
> +import { Image } from '../../../themes';
Both imports are from the same directory. Import them together.

2021-08-26 11:41 UTC, dsouzaedison commented on src/components/primitive/Icon-svg/icon-svg.component.props.ts
> +type Size = keyof typeof sizes;
You can directly use enums. It will serve as a type as well as value. Using typof is not recommended anywhere outside the themes folder.

2021-08-26 11:41 UTC, dsouzaedison commented on src/components/primitive/Icon-svg/icon-svg.component.props.ts
> +type Size = keyof typeof sizes;
export enum Sizes {}

2021-08-26 11:41 UTC, dsouzaedison commented on src/components/primitive/Icon-svg/icon-svg.component.props.ts
> +  color?: Color;
One thing to remember. Every prop should have at least one line of description explaining what it does. In this case, the name prop can be confusing to understand in the first attempt. So you can add

/**
\* Name of the SVG icon that is available in the theme
**/
name: Image

2021-08-26 11:41 UTC, dsouzaedison commented on src/components/primitive/Icon-svg/icon-svg.component.props.ts
> +  color?: Color;
You can refer Box PR to see how props file is written. This ensures quick documentation for developers using your component.

2021-08-26 11:41 UTC, dsouzaedison commented on src/components/primitive/Icon-svg/icon-svg.component.props.ts
> +export type { IconProps, Size };
This line is not required. Export the types directly on the same line where it's declared.

2021-08-26 11:41 UTC, dsouzaedison commented on src/components/primitive/Icon-svg/icon-svg.component.tsx
> +import { IconProps, sizes } from './icon-svg.component.props';
React is not imported in this component?
All the library imports go on top always. Local imports are at the bottom.

2021-08-26 11:41 UTC, dsouzaedison commented on src/components/primitive/Text/text.component.props.ts
> +  colors?: Color | any;
Why does this have any type?

2021-08-26 18:24 UTC, Koushith commented on src/components/primitive/Icon-svg/icon-svg.component.props.ts
> +type Size = keyof typeof sizes;
replaced interface with enum.

2021-08-26 18:25 UTC, Koushith commented on src/components/primitive/Icon-svg/icon-svg.component.props.ts
> +  color?: Color;
added a comment describing the properties.

2021-08-26 18:37 UTC, Koushith commented on src/components/primitive/Text/text.component.props.ts
> +  colors?: Color | any;
That was a quick hacky solution to test. I have fixed that. we have a separate ticket for updating the Text component.

2021-08-27 06:02 UTC, dsouzaedison approved these changes

2021-08-27 06:08 UTC, merged