#17 - Create Navlink component
safient/safient-client pull request #32
Opened 2021-09-02 15:07 UTC by cksadhukhan

## Description
Navlink Component added

## Screenshot
![Screenshot from 2021-09-02 20-36-23](https://user-images.githubusercontent.com/55362491/131868677-4165895f-1fa3-4de8-b852-813afce05e41.png)

## Tests
### Manual test cases run
_For each manual test case, list the steps to test or reproduce the PR._
- _Description of manual test 1_
- _Description of manual test 2_
- _Description of manual test 3_

## Platform tested
- [ ] Large
- [ ] Tablet
- [ ] Mobile

2021-09-02 15:25 UTC, dsouzaedison requested changes

2021-09-02 15:25 UTC, dsouzaedison commented on src/components/primitive/navlink/navlink.component.tsx
> +// @ts-ignore
Specify reason for ts-ignore always

2021-09-02 15:25 UTC, dsouzaedison commented on src/components/primitive/navlink/navlink.component.tsx
> +      <Box
What happens when you click this link?

2021-09-03 10:23 UTC, dsouzaedison commented on src/components/primitive/navlink/navlink.component.tsx
> +      onClick={onClick}
Does box support onClick?

2021-09-03 12:59 UTC, cksadhukhan commented on src/components/primitive/navlink/navlink.component.tsx
> +      onClick={onClick}
Yes

2021-09-05 07:10 UTC, dsouzaedison approved these changes

2021-09-05 08:42 UTC, merged