#20 - Create-HomeScreen
safient/safient-client pull request #50
Opened 2021-10-11 05:14 UTC by Koushith

## Description
- Adds Home Screen.
- Adds TopBar Component.
- Fixed overflow issues.
- Fixed headers on smaller devices.

## Screenshot
https://www.loom.com/share/278cf2c2b8104c54b6522ff4e1427474

![image](https://user-images.githubusercontent.com/30016242/138761127-8898ef10-952d-4eed-9fd9-c6c06f1d377e.png)
![image](https://user-images.githubusercontent.com/30016242/138763214-8d9bc3bc-a5e2-477f-951d-1e39ced994cd.png)

## Platform tested
- [x] web.
- [x] Mobile.

2021-10-12 04:04 UTC, dsouzaedison requested changes

2021-10-12 04:04 UTC, dsouzaedison commented on src/screens/home/home.screen.tsx
> +      <Title variant='contentHeader'>Safes</Title>
Is this hard-coded?

2021-10-12 04:04 UTC, dsouzaedison commented on src/screens/home/home.screen.tsx
> +          <SafeText variant='content'>Create Safe</SafeText>
Localise strings

2021-10-12 11:39 UTC, Koushith commented on src/screens/home/home.screen.tsx
> +          <SafeText variant='content'>Create Safe</SafeText>
Added in Create Card Component's PR. - https://github.com/safient/safient-client/pull/59

2021-10-25 20:21 UTC, Koushith commented on src/screens/home/home.screen.tsx
> +      <Title variant='contentHeader'>Safes</Title>
Removed all Hardcoded Values in the latest commit.

2021-10-27 05:26 UTC, koshikraj approved these changes

2021-10-27 07:08 UTC, merged