#52 - Create-card component
safient/safient-client pull request #59
Opened 2021-10-12 10:44 UTC by Koushith

## Description
- [x] Adds Reusable Create Card component.
- [x] Removed Test Data from Home Screen which was pushed accidentally. 

## Screenshot

![image](https://user-images.githubusercontent.com/30016242/136941345-82abd2a7-3f36-483c-9093-1935e95e612f.png)

## Platform tested
- [x] Web

2021-10-12 12:14 UTC, dsouzaedison requested changes

2021-10-12 12:14 UTC, dsouzaedison commented on src/components/primitive/create-card/create-card.component.styles.ts
> +export const SafeText = styled(Text)`
This is a generic card. It cannot have reference to business logic. Rename it to Label or something.

2021-10-12 12:14 UTC, dsouzaedison commented on src/i18n/locales/en.json
> +    "Safients": "Safients"
Property names must be in small cases!

2021-10-12 12:14 UTC, dsouzaedison commented on src/screens/home/home.screen.tsx
> +    <>
This wrapper is not required

2021-10-12 12:14 UTC, dsouzaedison commented on src/screens/home/home.screen.tsx
> +      <Text variant='title'>Dashboard</Text>
Why is this string hard-coded?

2021-10-13 05:43 UTC, Koushith commented on src/screens/home/home.screen.tsx
> +      <Text variant='title'>Dashboard</Text>
That was the Test Data that was pushed accidentally. I have cleared that in #20  Home Screen PR.

2021-10-13 05:43 UTC, Koushith commented on src/screens/home/home.screen.tsx
> +    <>
Removed in #20 HomeScreen PR.

2021-10-13 15:48 UTC, dsouzaedison approved these changes

2021-10-14 05:44 UTC, merged