#45 - Create a chip input component
safient/safient-client pull request #62
Opened 2021-10-25 05:59 UTC by cksadhukhan

- Chip Component added
 - Chip input component added
![Screenshot from 2021-10-25 11-25-41](https://user-images.githubusercontent.com/55362491/138641757-649d847f-8e18-4caa-bf1c-6f64bc3d4319.png)
![Screenshot from 2021-10-25 11-25-37](https://user-images.githubusercontent.com/55362491/138641779-96ef4ae1-06d9-4658-a6b0-8f1b8f8131ce.png)
![Screenshot from 2021-10-25 11-25-23](https://user-images.githubusercontent.com/55362491/138641787-d6962512-2cfc-4f8d-a920-7135c8280854.png)
![Screenshot from 2021-10-25 11-25-18](https://user-images.githubusercontent.com/55362491/138641806-39dab329-0e3e-4ac9-b787-65fe944d5bc4.png)

2021-10-25 14:18 UTC, koshikraj commented on src/components/primitive/chip-input/chip-input.component.tsx
> +const ChipContainer = styled.div`
Are we not supposed to use `Box` instead of `div`?

2021-10-25 14:18 UTC, koshikraj commented on src/components/primitive/chip/chip.component.tsx
> +const ChipBody = styled.div<{ index: number }>`
Are we not supposed to use Box instead of div?

2021-10-25 14:21 UTC, koshikraj commented
The input functions as intended 👍🏼

2021-10-28 04:59 UTC, dsouzaedison requested changes

2021-10-28 04:59 UTC, dsouzaedison commented on src/components/primitive/chip-input/chip-input.component.props.ts
> +  seedPhases: string[];
It should be `seedPhrases`!

2021-10-28 04:59 UTC, dsouzaedison commented on src/components/primitive/chip-input/chip-input.component.props.ts
> +  setSeedPhases: (seedPhases: string[]) => void;
Which component maintains the seed phrases?

2021-10-28 04:59 UTC, dsouzaedison commented on src/components/primitive/chip-input/chip-input.component.tsx
> +      if (value.trim().length === 0) return;
You don't need 0 comparison. JS does that for you. Just write `if(!value.trim())`

2021-10-28 04:59 UTC, dsouzaedison commented on src/components/primitive/chip-input/chip-input.component.props.ts
> +  seedPhases: string[];
Use a list instead of an array. That will make your job easy.

2021-10-28 04:59 UTC, dsouzaedison commented on src/components/primitive/chip-input/chip-input.component.tsx
> +      length === 0 ? '5rem' : `${length * 45 + 70}px`};
length ? '5rem' : `${length * 45 + 70}px`};

2021-10-28 04:59 UTC, dsouzaedison commented on src/components/primitive/chip-input/chip-input.component.tsx
> +  // const [seedPhases, setSeedPhases] = useState<string[]>([]);
Remove commented code

2021-10-28 04:59 UTC, dsouzaedison commented on src/components/primitive/chip-input/chip-input.component.tsx
> +    const newSeedPhases = seedPhases.filter((_, i) => {
Use the list and move the filter function there.

2021-10-28 04:59 UTC, dsouzaedison commented on src/components/primitive/chip-input/chip-input.component.tsx
> +    return seedPhases.length;
You don't need a function for one line code. The list would simplify this problem.

2021-10-28 04:59 UTC, dsouzaedison commented on src/components/primitive/chip-input/chip-input.component.tsx
> +  const isSeedPhaseFull = (): boolean => {
Add a function in SeedPhraseList called isFull()

2021-10-28 04:59 UTC, dsouzaedison commented on src/components/primitive/chip-input/chip-input.component.tsx
> +            ? '12 phases entered'
Why is this hard-coded?

2021-11-13 05:48 UTC, dsouzaedison requested changes

2021-11-13 05:48 UTC, dsouzaedison commented on src/components/primitive/chip-input/chip-input.component.tsx
> +      length === 0 ? '7rem' : `${length * 5 + 11}rem`} !important;
The calculations above are unclear. Either use appropriate constants, custom function, or add code comments.

2021-11-13 05:48 UTC, dsouzaedison commented on src/components/primitive/chip-input/chip-input.component.tsx
> +            ? t('chipInput.phrasesEntered')
Can you add support for placeholderTx prop inside Input component instead?

2021-11-13 05:51 UTC, dsouzaedison commented on src/components/primitive/chip-input/chip-input.component.tsx
>      <Container length={seedPhrasesLength()}>
Property length does not signify the value that needs to be passed. Please add a meaningful name.

2021-11-29 02:58 UTC, dsouzaedison approved these changes

2021-11-30 14:15 UTC, merged