WIP - #55 - Generic Modal
safient/safient-client pull request #68
Opened 2021-11-18 15:33 UTC by cksadhukhan

## Description
_A few sentences describing the overall goals of the pull request's commits._

## Screenshot
_For UI changes, include a screenshot of the changes._

## Tests
### Manual test cases run
_For each manual test case, list the steps to test or reproduce the PR._
- _Description of manual test 1_
- _Description of manual test 2_
- _Description of manual test 3_

## Platform tested
- [ ] Large
- [ ] Tablet
- [ ] Mobile

2021-12-23 07:07 UTC, Koushith requested changes

2021-12-23 07:07 UTC, Koushith commented on src/components/primitive/generi-cmodal/generic-modal.component.tsx
> +
@cksadhukhan can you please move this to separate styles file?

2021-12-23 07:07 UTC, Koushith commented on src/components/primitive/generi-cmodal/generic-modal.component.tsx
> +        </Box>
Title should be optional as this is a generic modal which can be reused along with loaders.

2021-12-23 07:07 UTC, Koushith commented on src/components/primitive/generi-cmodal/generic-modal.component.tsx
> +        </Box>
Even this should be optional.

2021-12-23 07:07 UTC, Koushith commented on src/components/primitive/generi-cmodal/generic-modal.component.tsx
> +  opacity: ${(props) => props.opacity};
I'm getting "opacity is not defined" while using this component.

2021-12-28 08:40 UTC, koshikraj approved these changes

2021-12-29 15:35 UTC, Koushith approved these changes

2021-12-29 15:35 UTC, Koushith commented
LGTM

2021-12-29 15:35 UTC, merged